FLATSELECT = SELECT FIELDLIST 
FROM WORKITEMS
[WHERE LOGICALEXPRESSION]
[ORDERBY ORDERBYFIELDLIST]
[ASOF DATETIME];
FIELDLIST = FIELD [COMMA FIELDLIST];
FIELD = IDENTIFIER | LSQBRACKET IDENTIFIER RSQBRACKET;
LOGICALEXPRESSION = [NOT| EVER] CONDITIONALEXPRESSION [(AND | OR) LOGICALEXPRESSION];
CONDITIONALEXPRESSION = LPAREN LOGICALEXPRESSION RPAREN 
| FIELD CONDITIONALOPERATOR VALUE
| FIELD [NOT] IN LPAREN VALUELIST RPAREN;
NUMBER = [MINUS] DIGITS;
VALUE = NUMBER | STRING | DATETIME | VARIABLE [(PLUS | MINUS) NUMBER] | TRUE | FALSE;
DATETIME = STRING;
VALUELIST = VALUE [COMMA VALUELIST];
CONDITIONALOPERATOR = EQUALS | NOTEQUALS | LESSTHAN | LESSOREQ | GREATERTHAN 
| GREATEROREQ | [EVER] [NOT] (LIKE | UNDER) | [NOT] CONTAINS | [NOT] CONTAINSWORDS
| [NOT] INGROUP;
CONTAINSWORDS = CONTAINS WORDS;
INGROUP = IN GROUP;
ORDERBYFIELDLIST = FIELD [ASC | DESC] [COMMA ORDERBYFIELDLIST];